In [1]:
import numpy as np

In [2]:
x = np.random.rand(4, 5)
print(x)

[[0.346406   0.15732192 0.36684779 0.41039399 0.95302168]
 [0.31632959 0.5167868  0.2750138  0.23135094 0.73359837]
 [0.11675215 0.49398981 0.91568886 0.51486528 0.44484973]
 [0.05870998 0.69717785 0.12314016 0.25535876 0.41108796]]


In [3]:
x.shape

(4, 5)

In [4]:
y = np.sum(x, axis=1)
print(y)

[2.23399138 2.07307949 2.48614583 1.5454747 ]


In [5]:
y.shape

(4,)