In [2]:
import numpy as np

In [2]:
x = np.random.rand(4, 5)
print(x)
a = np.random.rand(3, 1)
print(a)

[[0.2057552  0.81857595 0.190183   0.5617637  0.69705728]
 [0.28338388 0.62196403 0.1138183  0.61374584 0.41180623]
 [0.24789248 0.55088048 0.70609781 0.13015593 0.64708254]
 [0.4487238  0.87003532 0.22369262 0.64986862 0.6286576 ]]
[[0.83672403]
 [0.87972866]
 [0.38310356]]


In [3]:
x.shape

(4, 5)

In [4]:
y = np.sum(x, axis=1)
print(y)

[2.23399138 2.07307949 2.48614583 1.5454747 ]


In [5]:
y.shape

(4,)

In [14]:
np.random.rand()

0.6894848665031176

In [79]:
r = np.random.rand()
beta = r * 0.09 + 0.9
print(beta)

0.9188029624913465
